# Convert the read counts of multiple samples generated by featureCounts program
# from Subread software, according to specified experiment design file.

# User home directory
user_home <- Sys.getenv("HOME")

# Control parameters.
# Flag of verbose print.
verbose <- TRUE

# Directory for dataset.
dataset_dir <- file.path(user_home, "LINCSData/Datasets/Difference/LINCS.Dataset/Coen-Paper/Conv-GEO-Depot")
# Directory for read counts tables of dataset.
counts_dir <- file.path(dataset_dir, "Counts")

# Read the experiment design of multiple samples.
exprt_design_dir <- counts_dir
exprt_design_file_name <- "Conv-RNAseq-Experiment-Design.tsv"
exprt_design_file <- file.path(exprt_design_dir, exprt_design_file_name)
stopifnot(file.exists(exprt_design_file))
if(verbose) cat("Reading ", exprt_design_file, "...\n", sep="")
exprt_design <- read.delim(exprt_design_file, quote="", comment.char="#", check.names=FALSE, stringsAsFactors=FALSE)
exprt_design[,"ID"] <- paste(exprt_design[,"State"], exprt_design[,"Cell"], exprt_design[,"Experiment"], exprt_design[,"Dish"], sep=".")

# Process sample names and sort sample columns.
read_counts_file_main_name <- "Conv-RNAseq-Read-Counts"
read_counts_file_name <- paste(read_counts_file_main_name, "txt", sep=".")
read_counts_dir <- counts_dir
read_counts_file <- file.path(read_counts_dir, read_counts_file_name)
stopifnot(file.exists(read_counts_file))

# Read read counts table.
if(verbose) cat("Reading ", read_counts_file, "...\n", sep="")
read_counts <- read.delim(read_counts_file, quote="", comment.char="#", check.names=FALSE, stringsAsFactors=FALSE)

# Move Geneid column to row names.
rownames(read_counts) <- read_counts[,"Geneid"]
read_counts[,"Geneid"] <- NULL

# Extract read counts columns whose names contain "bam" keyword.
read_counts <- read_counts[,grepl("\\.bam$",colnames(read_counts))]

# Clean up sample names.
sample_names <- basename(colnames(read_counts))
colnames(read_counts) <- sapply(strsplit(sample_names,split="_"), function(x){return(paste0(x[1:4],collapse="."))})

# Sort samples according to experiment design.
stopifnot(setequal(colnames(read_counts), exprt_design[,"ID"]))
read_counts <- read_counts[,exprt_design[,"ID"]]

# Write converted read counts of selected samples.
convert_read_counts_dir <- counts_dir
convert_read_counts_file_name <- paste(read_counts_file_main_name, "tsv", sep=".")
convert_read_counts_file <- file.path(convert_read_counts_dir, convert_read_counts_file_name)
if(verbose) cat("Writing ", convert_read_counts_file, "...\n", sep="")
write.table(read_counts, file=convert_read_counts_file, quote=FALSE, na="", sep="\t", row.names=TRUE, col.names=TRUE)
